# ── Base de Datos ──────────────────────────────────────────
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PatrulleroAppDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=PatrulleroApp2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ── JPA / Hibernate ────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ── Puerto ─────────────────────────────────────────────────
server.port=8080

# ── App ────────────────────────────────────────────────────
spring.application.name=patrulleroapp-backend
spring.jpa.open-in-view=false