# ── Base de Datos MySQL Railway ────────────────────────────
spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:55731/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=VrWPobpTYCBIcIlKweNQQkZkmfhCzske
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ── Puerto ─────────────────────────────────────────────────
server.port=8080

# ── App ────────────────────────────────────────────────────
spring.application.name=patrulleroapp-backend

# ── Email ──────────────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rohirrimfelipe666@gmail.com
spring.mail.password=nkwm qenv lbdb emqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true